/* This file was automatically generated by CasADi 3.6.1.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[3] = {0, 0, 0};

/* Drone_ode_expl_ode_fun:(i0[6],i1[2],i2[])->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+6, w1, *w2=w+13, *w3=w+19, w4, *w5=w+32;
  /* #0: @0 = zeros(6x1) */
  casadi_clear(w0, 6);
  /* #1: @1 = input[0][3] */
  w1 = arg[0] ? arg[0][3] : 0;
  /* #2: (@0[0] = @1) */
  for (rr=w0+0, ss=(&w1); rr!=w0+1; rr+=1) *rr = *ss++;
  /* #3: @1 = input[0][4] */
  w1 = arg[0] ? arg[0][4] : 0;
  /* #4: (@0[1] = @1) */
  for (rr=w0+1, ss=(&w1); rr!=w0+2; rr+=1) *rr = *ss++;
  /* #5: @1 = input[0][5] */
  w1 = arg[0] ? arg[0][5] : 0;
  /* #6: (@0[2] = @1) */
  for (rr=w0+2, ss=(&w1); rr!=w0+3; rr+=1) *rr = *ss++;
  /* #7: @1 = 0 */
  w1 = 0.;
  /* #8: (@0[3] = @1) */
  for (rr=w0+3, ss=(&w1); rr!=w0+4; rr+=1) *rr = *ss++;
  /* #9: @1 = -9.81 */
  w1 = -9.8100000000000005e+00;
  /* #10: (@0[4] = @1) */
  for (rr=w0+4, ss=(&w1); rr!=w0+5; rr+=1) *rr = *ss++;
  /* #11: @1 = 0 */
  w1 = 0.;
  /* #12: (@0[5] = @1) */
  for (rr=w0+5, ss=(&w1); rr!=w0+6; rr+=1) *rr = *ss++;
  /* #13: @2 = zeros(6x1) */
  casadi_clear(w2, 6);
  /* #14: @3 = zeros(6x2) */
  casadi_clear(w3, 12);
  /* #15: @1 = input[0][2] */
  w1 = arg[0] ? arg[0][2] : 0;
  /* #16: @4 = sin(@1) */
  w4 = sin( w1 );
  /* #17: @4 = (-@4) */
  w4 = (- w4 );
  /* #18: (@3[3] = @4) */
  for (rr=w3+3, ss=(&w4); rr!=w3+4; rr+=1) *rr = *ss++;
  /* #19: @4 = 0 */
  w4 = 0.;
  /* #20: (@3[9] = @4) */
  for (rr=w3+9, ss=(&w4); rr!=w3+10; rr+=1) *rr = *ss++;
  /* #21: @1 = cos(@1) */
  w1 = cos( w1 );
  /* #22: (@3[4] = @1) */
  for (rr=w3+4, ss=(&w1); rr!=w3+5; rr+=1) *rr = *ss++;
  /* #23: @1 = 0 */
  w1 = 0.;
  /* #24: (@3[10] = @1) */
  for (rr=w3+10, ss=(&w1); rr!=w3+11; rr+=1) *rr = *ss++;
  /* #25: @1 = 0 */
  w1 = 0.;
  /* #26: (@3[5] = @1) */
  for (rr=w3+5, ss=(&w1); rr!=w3+6; rr+=1) *rr = *ss++;
  /* #27: @1 = 50 */
  w1 = 50.;
  /* #28: (@3[11] = @1) */
  for (rr=w3+11, ss=(&w1); rr!=w3+12; rr+=1) *rr = *ss++;
  /* #29: @1 = input[1][0] */
  w1 = arg[1] ? arg[1][0] : 0;
  /* #30: @4 = input[1][1] */
  w4 = arg[1] ? arg[1][1] : 0;
  /* #31: @5 = vertcat(@1, @4) */
  rr=w5;
  *rr++ = w1;
  *rr++ = w4;
  /* #32: @2 = mac(@3,@5,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w3+j, tt=w5+i*2; k<2; ++k) *rr += ss[k*6]**tt++;
  /* #33: @0 = (@0+@2) */
  for (i=0, rr=w0, cs=w2; i<6; ++i) (*rr++) += (*cs++);
  /* #34: output[0][0] = @0 */
  casadi_copy(w0, 6, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 34;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
